CREATE TABLE translators 
(
    id	INT PRIMARY KEY,
    name	VARCHAR(512)
);

INSERT INTO translators (id, name) VALUES ('1', 'Adrian Nathan West');
INSERT INTO translators (id, name) VALUES ('2', 'Alison L. Strayer');
INSERT INTO translators (id, name) VALUES ('3', 'Angela Rodel');
INSERT INTO translators (id, name) VALUES ('4', 'Aniruddhan Vasudevan');
INSERT INTO translators (id, name) VALUES ('5', 'Anna Moschovakis');
INSERT INTO translators (id, name) VALUES ('6', 'Anne McLean');
INSERT INTO translators (id, name) VALUES ('7', 'Annelise Finegan Wasmoen');
INSERT INTO translators (id, name) VALUES ('8', 'Anton Hur');
INSERT INTO translators (id, name) VALUES ('9', 'Antonia Lloyd-Jones');
INSERT INTO translators (id, name) VALUES ('10', 'Camilo A. Ramirez');
INSERT INTO translators (id, name) VALUES ('11', 'Carolina Orloff');
INSERT INTO translators (id, name) VALUES ('12', 'Charlotte Barslund');
INSERT INTO translators (id, name) VALUES ('13', 'Charlotte Collins');
INSERT INTO translators (id, name) VALUES ('14', 'Chen Zeping');
INSERT INTO translators (id, name) VALUES ('15', 'Daisy Rockwell');
INSERT INTO translators (id, name) VALUES ('16', 'Damion Searls');
INSERT INTO translators (id, name) VALUES ('17', 'Daniel Hahn');
INSERT INTO translators (id, name) VALUES ('18', 'Daniel Levin Becker');
INSERT INTO translators (id, name) VALUES ('19', 'Darryl Sterk');
INSERT INTO translators (id, name) VALUES ('20', 'David Boyd');
INSERT INTO translators (id, name) VALUES ('21', 'David Doherty');
INSERT INTO translators (id, name) VALUES ('22', 'Deborah Bragan-Turner');
INSERT INTO translators (id, name) VALUES ('23', 'Deborah Smith');
INSERT INTO translators (id, name) VALUES ('24', 'Eileen Myles');
INSERT INTO translators (id, name) VALUES ('25', 'Elisabeth Jaquette');
INSERT INTO translators (id, name) VALUES ('26', 'Elizabeth Heighway');
INSERT INTO translators (id, name) VALUES ('27', 'Fiona Mackintosh');
INSERT INTO translators (id, name) VALUES ('28', 'Frances Riddle');
INSERT INTO translators (id, name) VALUES ('29', 'Frank Wynne');
INSERT INTO translators (id, name) VALUES ('30', 'George Szirtes');
INSERT INTO translators (id, name) VALUES ('31', 'Iona Macintyre');
INSERT INTO translators (id, name) VALUES ('32', 'Jackie Smith');
INSERT INTO translators (id, name) VALUES ('33', 'Jae Won Chung');
INSERT INTO translators (id, name) VALUES ('34', 'Jen Calleja');
INSERT INTO translators (id, name) VALUES ('35', 'Jennifer Croft');
INSERT INTO translators (id, name) VALUES ('36', 'Jennifer Higgins');
INSERT INTO translators (id, name) VALUES ('37', 'Jeremy Tiang');
INSERT INTO translators (id, name) VALUES ('38', 'Jessica Cohen');
INSERT INTO translators (id, name) VALUES ('39', 'John Batki');
INSERT INTO translators (id, name) VALUES ('40', 'Jonathan Wright');
INSERT INTO translators (id, name) VALUES ('41', 'Karen Gernant');
INSERT INTO translators (id, name) VALUES ('42', 'Katy Derbyshire');
INSERT INTO translators (id, name) VALUES ('43', 'Leslie Camhi');
INSERT INTO translators (id, name) VALUES ('44', 'Margaret Jull Costa');
INSERT INTO translators (id, name) VALUES ('45', 'Marilyn Booth');
INSERT INTO translators (id, name) VALUES ('46', 'Mark Polizzotti');
INSERT INTO translators (id, name) VALUES ('47', 'Martin Aitken');
INSERT INTO translators (id, name) VALUES ('48', 'Megan McDowell');
INSERT INTO translators (id, name) VALUES ('49', 'Michele Hutchinson');
INSERT INTO translators (id, name) VALUES ('50', 'Michiel Heyns');
INSERT INTO translators (id, name) VALUES ('51', 'Natasha Wimmer');
INSERT INTO translators (id, name) VALUES ('52', 'Nichola Smalley');
INSERT INTO translators (id, name) VALUES ('53', 'Nicole d''Amonville Alegría');
INSERT INTO translators (id, name) VALUES ('54', 'Ottilie Mulzet');
INSERT INTO translators (id, name) VALUES ('55', 'Reuben Woolley');
INSERT INTO translators (id, name) VALUES ('56', 'Richard Philcox');
INSERT INTO translators (id, name) VALUES ('57', 'Rosalind Harvey');
INSERT INTO translators (id, name) VALUES ('58', 'Ross Benjamin');
INSERT INTO translators (id, name) VALUES ('59', 'Ruth Martin');
INSERT INTO translators (id, name) VALUES ('60', 'Sam Bett');
INSERT INTO translators (id, name) VALUES ('61', 'Sam Garrett');
INSERT INTO translators (id, name) VALUES ('62', 'Sam Taylor');
INSERT INTO translators (id, name) VALUES ('63', 'Sarah Moses');
INSERT INTO translators (id, name) VALUES ('64', 'Sasha Dugdale');
INSERT INTO translators (id, name) VALUES ('65', 'Shaun Whiteside');
INSERT INTO translators (id, name) VALUES ('66', 'Sherilyn Nicolette Hellberg');
INSERT INTO translators (id, name) VALUES ('67', 'Simon Pare');
INSERT INTO translators (id, name) VALUES ('68', 'Sophie Hughes');
INSERT INTO translators (id, name) VALUES ('69', 'Sophie Lewis');
INSERT INTO translators (id, name) VALUES ('70', 'Sora Kim-Russell');
INSERT INTO translators (id, name) VALUES ('71', 'Stephen Snyder');
INSERT INTO translators (id, name) VALUES ('72', 'Susan Bernofsky');
INSERT INTO translators (id, name) VALUES ('73', 'Tiffany Tsao');
INSERT INTO translators (id, name) VALUES ('74', 'Ngũgĩ wa Thiong''o');
